services:
  - type: web
    name: isbn-komarc-backend
    env: python
    plan: free
    buildCommand: python - m pip install -- upgrade pip && python - m pi
    startCommand: pithon - m uvicorn backend_api:app --host 0.0.0.0 --
    autoDeploy: true
    envVars:
      - key: ALADIN_TTB_KEY
        sync: false
      - key: NL_SEOKJI_CERT_KEY
        sync: false
