services:
  - type: web
    name: isbn-komarc-backend
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python -m uvicorn backend_api:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ALADIN_TTB_KEY
        value: ttbboyeong09010919001
        sync: false
      - key: NL_SEOKJI_CERT_KEY
        sync: false
